export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REG_ROUTE = '/reg'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const ItemPage = '/shop'
